site_name: Python Test Framework
site_url: https://python-test-engineer.github.io

# Configuring a theme
# theme:
#   name: material
#   features:
# - navigation.tabs
# - navigation.sections

# Configuring a theme
theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

      primary: purple
      accent: purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: purple
      accent: orange
# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  # - mdx_math:
  #     enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    # - icon: "fontawesome/brands/twitter"
    #   link: "https://twitter.com/piris314en"

# Page tree
nav:
  - "Home": "index.md"

  - "Django Testing":
      - "About": "django/about.md"
      - "Setup": "django_testing/setup"
      - "Apps": "django_testing/apps.md"
      - "Tests": "django_testing/tests.md"
  - "PyTest":
      - "PyTest Basic": "pytest/pytest_basic.md"
      - "PyTest": "pytest/pytest.md"
      - "Tutorial 1": "pytest/tutorial_1.md"
      - "Tutorial 2": "pytest/tutorial_2.md"
      - "Mock and Patch": "pytest/mock_patch.md"
  - "Playwright and API":
      - "Testing Playgrounds": "playwright_api/testing_playgrounds.md"
      - "API": "playwright_api/api.md"
      - "Playwright": "playwright_api/playwright.md"
  - "Hypothesis":
      - "About": "hypothesis/index.md"
  - "About Craig":
      - "craig/index.md"

copyright: |
  &copy; 2024 <a href="https://github.com/Python-Test-Engineer"  target="_blank" rel="noopener">Craig West</a>
