site_name: Python Test Framework
site_url: https://python-test-engineer.github.io

# Configuring a theme
theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  # - mdx_math:
  #     enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/piris314en"

# Page tree
nav:
  - "Home": "index.md"
  - "Craig":
      - "craig/index.md"
      - "craig/deployment.md"
      - "craig/configuration.md"
      - "craig/example.md"
      - "craig/install.md"
      - "craig/release_notes.md"
  - "Getting started":
      - "Download boilerplate": "getting-started/download-boilerplate.md"
      - "pipenv": "getting-started/pipenv.md"
      - "invoke": "getting-started/invoke.md"
      - "Docker": "getting-started/docker.md"
      - "pip": "getting-started/pip.md"
  - "Hosting and Deployment":
      - "Combinations": "hosting-and-deployment/combinations.md"
      - "Netlify": "hosting-and-deployment/netlify.md"
      - "GitHub Pages": "hosting-and-deployment/github-pages.md"
      - "GitLab Pages": "hosting-and-deployment/gitlab-pages.md"
      - "AWS Amplify Console": "hosting-and-deployment/aws-amplify-console.md"
  - "Extensions":
      - "MathJax": "extensions/mathjax.md"
      - "Code Hilite": "extensions/code-hilite.md"
      - "Footnote": "extensions/footnote.md"
