site_name: Python Test Framework
site_url: https://python-test-engineer.github.io

# Configuring a theme
# theme:
#   name: material
#   features:
# - navigation.tabs
# - navigation.sections

# Configuring a theme
theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

      primary: purple
      accent: purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: purple
      accent: orange
# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  # - mdx_math:
  #     enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/piris314en"

# Page tree
nav:
  - "Home": "index.md"

  - "Django Testing":
      - "MathJax": "django_testing/mathjax.md"
      - "Code Hilite": "django_testing/code-hilite.md"
      - "Footnote": "django_testing/footnote.md"
  - "PyTest":
      - "Download boilerplate": "pytest/download-boilerplate.md"
      - "pipenv": "pytest/pipenv.md"
      - "invoke": "pytest/invoke.md"
      - "Docker": "pytest/docker.md"
      - "pip": "pytest/pip.md"
  - "Playwright and API":
      - "Combinations": "paywright_api/combinations.md"
      - "Netlify": "paywright_api/netlify.md"
      - "GitHub Pages": "paywright_api/github-pages.md"
      - "GitLab Pages": "paywright_api/gitlab-pages.md"
      - "AWS Amplify Console": "paywright_api/aws-amplify-console.md"
  - "Hypothes":
      - "About": "hypothesis/index.md"
  - "About Craig":
      - "craig/index.md"
      - "craig/deployment.md"
      - "craig/configuration.md"
      - "craig/example.md"
      - "craig/install.md"
      - "craig/release_notes.md"
copyright: |
  &copy; 2024 <a href="https://github.com/Python-Test-Engineer"  target="_blank" rel="noopener">Craig West</a>
