site_name: Python Test Framework
site_description: "Python Test Framework"

repo_url: https://github.com/Python-Test-Engineer/PYTHON-TEST-FRAMEWORK
repo_name: Python-Test-Engineer/PYTHON-TEST-FRAMEWORK

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "blue"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "blue"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/Python-Test-Engineer/"

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


# Page tree
nav:
  - "Home": "index.md"

  - "Django Testing":
      - "Setup": "django_testing/setup"
      - "Apps": "django_testing/apps.md"
      - "Tests": "django_testing/tests.md"
  - "PyTest":
      - "PyTest Basic": "pytest/pytest_basic.md"
      - "PyTest": "pytest/pytest.md"
  - "Playwright Testing":
      - "Playwright": "playwright_api/playwright.md"
      - "Testing Playgrounds": "playwright_api/testing_playgrounds.md"
  - "API Testing":
      - "About": "playwright_api/api.md"
  - "Hypothesis":
      - "About Hypothesis": "hypothesis/index.md"
  - "About Craig": "craig/index.md"


copyright: |
  &copy; 2024 <a href="https://github.com/Python-Test-Engineer"  target="_blank" rel="noopener">Craig West - PythonTestEngineer.co.uk</a>
