site_name: Python Test Framework
site_url: https://python-test-engineer.github.io

# Configuring a theme
theme:
  name: material
  features:
    - navigation.tabs

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  # - mdx_math:
  #     enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

# Page tree
nav:
  - "Home": "index.md"
  - "Material for MkDocs": "material-for-mkdocs.md"
  - "Getting started":
      - "Download boilerplate": "getting-started/download-boilerplate.md"
      - "pipenv": "getting-started/pipenv.md"
      - "invoke": "getting-started/invoke.md"
      - "Docker": "getting-started/docker.md"
      - "pip": "getting-started/pip.md"
  - "Hosting and Deployment":
      - "Combinations": "hosting-and-deployment/combinations.md"
      - "Netlify": "hosting-and-deployment/netlify.md"
      - "GitHub Pages": "hosting-and-deployment/github-pages.md"
      - "GitLab Pages": "hosting-and-deployment/gitlab-pages.md"
      - "AWS Amplify Console": "hosting-and-deployment/aws-amplify-console.md"
  - "Extensions":
      - "MathJax": "extensions/mathjax.md"
      - "Code Hilite": "extensions/code-hilite.md"
      - "Footnote": "extensions/footnote.md"
  - "License": "license.md"
